---
title: Análise exploratório dataset  **dados_execicios.csv**
author: Rafael De Pauli Baptista
date: 25/05/2024
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(kableExtra)
library(dplyr)
library(ggplot2)
```

# Descrição do dataset
## Visualização
```{r}
dados_exercicios <- read.csv("dados_exercicio.csv") %>% select(
    Gender, Age, Occupation, Sleep.Duration, Quality.of.Sleep, Physical.Activity.Level,
    Stress.Level, BMI.Category, Heart.Rate, Daily.Steps, Sleep.Disorder
)
dados_exercicios <- dados_exercicios %>%
    dplyr::mutate(BMI.Category = ifelse(dados_exercicios$BMI.Category == "Normal Weight", yes = "Normal", no = BMI.Category))

dados_exercicios$Gender <- factor(dados_exercicios$Gender)
dados_exercicios$Occupation <- factor(dados_exercicios$Occupation)
dados_exercicios$BMI.Category <- factor(dados_exercicios$BMI.Category, levels = c("Normal", "Overweight", "Obese"))
dados_exercicios$Sleep.Disorder <- factor(dados_exercicios$Sleep.Disorder)

head(dados_exercicios) %>%
    kbl() %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

## Sumário
```{r}
summary(dados_exercicios) %>%
    kbl() %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

# Análise variáveis qualitativas
## Gênero
```{r}
# Calcular os valores percentuais
dados_relativo_genero <- round(prop.table(table(dados_exercicios$Gender)) * 100, 1)

# Criar o gráfico de barras
barplot_genero <- barplot(dados_relativo_genero, xlab = "Gêneros", ylab = "%", ylim = c(0, 100))

# Adicionar os valores percentuais nas barras
text(x = barplot_genero, y = dados_relativo_genero + 5, labels = paste0(dados_relativo_genero, "%"), col = "black", cex = 1)
```

## Ocupação
```{r}
dados_relativo_ocupacao <- sort(round(prop.table(table(dados_exercicios$Occupation)) * 100, 1), decreasing = TRUE)

# Criar o gráfico de barras
barplot_ocupacao <- barplot(dados_relativo_ocupacao, xlab = "Ocupação", ylab = "%", ylim = c(0, 30))

# Adicionar os valores percentuais nas barras
text(x = barplot_ocupacao, y = dados_relativo_ocupacao + 5, labels = paste0(dados_relativo_ocupacao, "%"), col = "black", cex = 1)
```

